### ISSUE TITLE
Error when using global variable.

### ISSUE THREAD

**Issue by kvnwolf** [termi/es6-transpiler#13]
I'm trying to compile a script in which I'm calling some global objects, in this case the `document` object and the compiler fails.

This is my `app.js` file:

``` javascript
class Board {
  constructor(el) {
    this.element = document.getElementById(el);
  }
}
```

And this is the output:

``` bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 
gulp-es6-transpiler: line 3: reference to unknown global variable document
    at /Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp-es6-transpiler/index.js:29:14
    at wrappedMapper (/Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp-es6-transpiler/node_modules/event-stream/node_modules/map-stream/index.js:76:19)
    at Stream.stream.write (/Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp-es6-transpiler/node_modules/event-stream/node_modules/map-stream/index.js:88:21)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at queueData (/Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp/node_modules/event-stream/node_modules/map-stream/index.js:38:21)
    at next (/Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp/node_modules/event-stream/node_modules/map-stream/index.js:68:5)
    at /Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp/node_modules/event-stream/node_modules/map-stream/index.js:77:7
    at /Users/kevinwolf/projects/Sandbox/ES6-Learnbox/node_modules/gulp/lib/createInputStream/bufferFile.js:7:5
    at fs.js:266:14
```

Any thoughts?

**Comment by termi** [comment]
Sorry for delay - I was on Christmas holiday. I think it's wrong [olov/defs](https://github.com/olov/defs) options

**Comment by maksnester** [comment]
Hello. 
I met the same problem. Here is the pretty dummy es6 source:

```
class User {
    constructor(name) {
        this.name = name;
    }
    sayHi() {
        alert(this.name); // troubles here
    }
}

var user = new User("Max");

```

Here is the error:  

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: line 6: reference to unknown global variable alert
```

How can I fix this?

**Comment by maksnester** [comment]
By the way, something like `document.getElementById('koko');` instead of `alert` works fine.
